-- MySQL Script generated by MySQL Workbench
-- 08/30/14 13:55:14
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sales_reports_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sales_reports_database` DEFAULT CHARACTER SET latin1 ;
USE `sales_reports_database` ;

-- -----------------------------------------------------
-- Table `sales_reports_database`.`sales_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales_reports_database`.`sales_reports` (
  `CarId` INT(11) NOT NULL,
  `SalesReportFilePath` VARCHAR(50) NOT NULL,
  `CarModel` VARCHAR(50) NOT NULL,
  `CarMake` VARCHAR(50) NOT NULL,
  `QuantitySold` INT(11) NOT NULL,
  `TotalIncome` DECIMAL(10,0) NOT NULL,
  UNIQUE INDEX `sales_report_file_path_UNIQUE` (`SalesReportFilePath` ASC),
  UNIQUE INDEX `car-id_UNIQUE` (`CarId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
