-- MySQL Script generated by MySQL Workbench
-- 08/30/14 02:13:11
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sales_reports_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sales_reports_database` DEFAULT CHARACTER SET latin1 ;
USE `sales_reports_database` ;

-- -----------------------------------------------------
-- Table `sales_reports_database`.`sales_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales_reports_database`.`sales_reports` (
  `car-id` INT(11) NOT NULL,
  `sales-report-file-path` VARCHAR(50) NOT NULL,
  `car-model` VARCHAR(50) NOT NULL,
  `car-make` VARCHAR(50) NOT NULL,
  `quantity-sold` INT(11) NOT NULL,
  `total-income` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`car-id`),
  UNIQUE INDEX `sales_report_file_path_UNIQUE` (`sales-report-file-path` ASC),
  UNIQUE INDEX `car-id_UNIQUE` (`car-id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE USER 'user' IDENTIFIED BY '12345';

GRANT ALL ON `mydb`.* TO 'user';
GRANT ALL ON `sales_reports_database`.* TO 'user';
GRANT SELECT ON TABLE `mydb`.* TO 'user';
GRANT SELECT ON TABLE `sales_reports_database`.* TO 'user';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'user';
GRANT SELECT, INSERT, TRIGGER ON TABLE `sales_reports_database`.* TO 'user';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'user';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `sales_reports_database`.* TO 'user';
GRANT EXECUTE ON ROUTINE `mydb`.* TO 'user';
GRANT EXECUTE ON ROUTINE `sales_reports_database`.* TO 'user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
