#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CarSalesSystem.Model	
{
	public partial class Sales_report
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _carid;
		public virtual int CarId
		{
			get
			{
				return this._carid;
			}
			set
			{
				this._carid = value;
			}
		}
		
		private string _salesreportfilepath;
		public virtual string SalesReportFilePath
		{
			get
			{
				return this._salesreportfilepath;
			}
			set
			{
				this._salesreportfilepath = value;
			}
		}
		
		private string _carmodel;
		public virtual string CarModel
		{
			get
			{
				return this._carmodel;
			}
			set
			{
				this._carmodel = value;
			}
		}
		
		private string _carmake;
		public virtual string CarMake
		{
			get
			{
				return this._carmake;
			}
			set
			{
				this._carmake = value;
			}
		}
		
		private int _quantitysold;
		public virtual int QuantitySold
		{
			get
			{
				return this._quantitysold;
			}
			set
			{
				this._quantitysold = value;
			}
		}
		
		private long _totalincome;
		public virtual long TotalIncome
		{
			get
			{
				return this._totalincome;
			}
			set
			{
				this._totalincome = value;
			}
		}
		
	}
}
#pragma warning restore 1591
